spring:
  config:
    import: file:env.properties
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_LOGIN}
    password: ${DB_PASSWORD}
    url: ${DB_PATH}
  flyway:
    enabled: true
    baseline-on-migrate: false
